# Generated by Django 2.1.7 on 2019-03-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('taxi_number', models.IntegerField()),
                ('busy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxiTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('bus_trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TaxiTrips', to='taxi.BusTrip')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TaxiTripsD', to='taxi.Location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TaxiTripsO', to='taxi.Location')),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Trips', to='taxi.Taxi')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='TaxiTrips', to='taxi.User'),
        ),
        migrations.AddField(
            model_name='bustrip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BusTripsD', to='taxi.Location'),
        ),
        migrations.AddField(
            model_name='bustrip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BusTripsO', to='taxi.Location'),
        ),
    ]
