# Generated by Django 2.2 on 2019-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='status',
            field=models.CharField(choices=[('CA', 'CANCELLED'), ('AC', 'ACTIVE'), ('PE', 'PENDING'), ('PA', 'PAST')], default='PE', max_length=2),
        ),
    ]
