# Generated by Django 2.2 on 2019-04-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='taxitrip',
            old_name='date',
            new_name='departure_date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='state',
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='locations', to='taxi.City'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='cities', to='taxi.State'),
        ),
        migrations.AddField(
            model_name='taxi',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='taxis', to='taxi.City'),
        ),
    ]
