# Generated by Django 2.2 on 2019-04-25 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card',
            field=models.CharField(default=1234567812345678, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='busTripsD', to='taxi.Location'),
        ),
        migrations.AlterField(
            model_name='bustrip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='busTripsO', to='taxi.Location'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='bus_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxiTrips', to='taxi.BusTrip'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxiTripsD', to='taxi.Location'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxiTripsO', to='taxi.Location'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='taxi.Taxi'),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxiTrips', to='taxi.User'),
        ),
    ]
