# Generated by Django 2.2 on 2019-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20190430_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxitrip',
            name='taxi_rating',
            field=models.PositiveSmallIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='user_rating',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
