# Generated by Django 2.2 on 2019-04-25 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20190425_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taxiTrips', to='taxi.User'),
        ),
    ]
