# Generated by Django 2.2 on 2019-04-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20190425_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi',
            name='busy',
        ),
    ]
