# Generated by Django 2.2 on 2019-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20190505_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustrip',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
