# Generated by Django 2.2 on 2019-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_bustrip_round_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='taxi_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxitrip',
            name='user_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
