# Generated by Django 2.2 on 2019-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_auto_20190505_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=25.6714),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=-100.309),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='distance',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
