# Generated by Django 2.2 on 2019-05-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_auto_20190507_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxitrip',
            old_name='distance',
            new_name='distance_meters',
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='distance_string',
            field=models.CharField(default='En corto se acaba', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='time_seconds',
            field=models.BigIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxitrip',
            name='time_string',
            field=models.CharField(default='Instantaneo', max_length=100),
            preserve_default=False,
        ),
    ]
