# Generated by Django 2.2 on 2019-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20190507_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bustrip',
            old_name='arrival_date',
            new_name='first_arrival_date',
        ),
        migrations.RenameField(
            model_name='bustrip',
            old_name='departure_date',
            new_name='first_departure_date',
        ),
        migrations.AddField(
            model_name='bustrip',
            name='second_arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bustrip',
            name='second_departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
