# Generated by Django 2.2 on 2019-05-08 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20190508_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxitrip',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 21, 25, 59, 636262, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
